composer.json

Signed-off-by: Eric <ehock7229@outlook.com>
This should fix the composer install scripts, and auto publish assets.

update composer.json scripts

---

app/Http/Controllers/ConversationsController.php
composer.json

Fix conversationscontroller

---

app/Presenters/Topic.php

…rum view works again
Signed-off-by: Eric <ehock7229@outlook.com>
This fixes the Topic presenter so we can show the actual forums in a category

Fix the Topic presenter 

---

app/Http/Requests/Conversations/CreateRequest.php
app/Http/Requests/Conversations/ParticipantRequest.php
app/Http/Requests/Conversations/ReplyRequest.php
app/Http/Requests/Post/LikePostRequest.php
app/Http/Requests/Post/QuotePostRequest.php
app/Http/Requests/Search/SearchRequest.php
app/Http/Requests/Topic/CreateRequest.php
app/Http/Requests/Topic/ReplyRequest.php

Signed-off-by: Eric <ehock7229@outlook.com>
Fix the imports for the Guard in the requests, should fix some routing issues.

fix guard contract imports

---

app/Http/Requests/Conversations/CreateRequest.php
app/Http/Requests/Conversations/ParticipantRequest.php
app/Http/Requests/Conversations/ReplyRequest.php
app/Http/Requests/Post/LikePostRequest.php
app/Http/Requests/Post/QuotePostRequest.php
app/Http/Requests/Search/SearchRequest.php
app/Http/Requests/Topic/CreateRequest.php
app/Http/Requests/Topic/ReplyRequest.php
resources/views/topic/quickreply.twig
resources/views/topic/reply.twig

This fixes issue #189 for the routing arrays in the views. Parser will need to be fixed as shown below.
[![https://gyazo.com/fa367f67484d13e8d2f7c8541f1d3cf1](https://i.gyazo.com/fa367f67484d13e8d2f7c8541f1d3cf1.png)](https://gyazo.com/fa367f67484d13e8d2f7c8541f1d3cf1)

Fix 189 reply views

---

resources/lang/admin/en/general.php
resources/views/header/welcomeblock_member.twig

Signed-off-by: Eric <ehock7229@outlook.com>
Adds a link to the user menu if the user has the permission canEnterACP

add link to admin dashboard if user has canEnterACP permission

---

app/Http/Controllers/AccountController.php

Fixes missing trans function

---

app/Likes/Database/Repositories/Eloquent/LikesRepository.php

Increments and decrements likes, mark content (posts) as edited.

Ignore timestamps on like/unlike content

---

app/Http/Controllers/Auth/PasswordController.php
app/Http/Controllers/CaptchaController.php
app/Http/Controllers/ModerationController.php
app/Http/Controllers/PollController.php
app/Presenters/Conversation.php
app/Presenters/Poll.php

Fixes some Guard contract import

Fixes some Guard contract import

---

app/Database/Models/Poll.php
app/Database/Models/Post.php
app/Database/Models/Topic.php
app/Database/Models/User.php
app/Likes/Twig/Extensions/RenderLikes.php

Removed timestamps from a  few models. Also fixes #204.

Removing timestamps

---

app/Http/Controllers/TopicController.php
app/Http/breadcrumbs.php

Fixes #213 ErrorException when editing post

---

app/Database/Repositories/Eloquent/ConversationMessageRepository.php
app/Database/Repositories/Eloquent/PostRepository.php
app/Http/Controllers/ConversationsController.php
app/Http/Controllers/TopicController.php

Using `Parser` rather than `MessageFormatter`.

Fixing #230.

---

app/Http/Controllers/ForumController.php
app/Widgets/Registry.php
app/Widgets/ServiceProvider.php
app/Widgets/Twig/Widget.php
app/Widgets/WidgetInterface.php
app/Widgets/Widgets/ForumListWidget.php
app/Widgets/Widgets/RenderViewWidget.php
app/Widgets/Widgets/UsersOnlineWidget.php
config/app.php
config/twigbridge.php
resources/views/forum/index.twig
resources/views/widgets/forum_list.twig
resources/views/widgets/users_online.twig

The widget system allows the creating and management of widgets and widget positions. Widgets can be simple, or complex. Widget positions hold none to many widgets that are rendered in the order they are added to the position.

Working on initial widget system.

---

app/Database/Repositories/Eloquent/PostRepository.php
app/Presenters/PostPresenter.php
resources/views/topic/quickreply.twig
resources/views/topic/reply.twig

Fixed some errors while adding new post.

Fix adding posts

---

app/Database/Repositories/Eloquent/RoleRepository.php
app/Database/Repositories/Eloquent/UserRepository.php
app/Database/Repositories/RoleRepositoryInterface.php
app/Database/Repositories/UserRepositoryInterface.php
app/Http/Controllers/Auth/AuthController.php
app/Providers/AppServiceProvider.php

I f* up last PR. This contains clean code.

Use repositories instead of models Fix #227

---

app/Database/Repositories/Eloquent/TopicRepository.php

Set created at and updated while creating a new topic

fixed topic creation

---

app/Http/Controllers/Admin/Users/UserController.php
app/Http/breadcrumbs.php
app/Http/routes.php
resources/assets/sass/admin/_main.scss
resources/lang/admin/en/users.php
resources/views/admin/partials/users/user_form.twig
resources/views/admin/users/add.twig
resources/views/admin/users/edit.twig
resources/views/admin/users/list.twig
resources/views/layouts/admin.twig

Added Users Management that allows admins to edit or add users

Added Users Management

---

app/Presenters/UserPresenter.php
app/Providers/AppServiceProvider.php

My earlier changes in UserPresenter were mistake.

Follow style guide

---

app/Database/Repositories/Eloquent/PostRepository.php
app/Database/Repositories/Eloquent/TopicRepository.php
app/Presenters/TopicPresenter.php

Edited some files to allow guests to send threads and posts

Fixed create topics/posts to guests

---

app/Moderation/Moderations/Approve.php
app/Moderation/Moderations/Close.php
app/Moderation/Moderations/DeletePost.php
app/Moderation/Moderations/DeleteTopic.php
app/Moderation/Moderations/MergePosts.php
app/Moderation/Moderations/MovePost.php
app/Moderation/Moderations/MoveTopic.php
app/Moderation/Moderations/Stick.php
resources/lang/en/forum.php
resources/lang/en/moderation.php
resources/views/partials/moderation/logs/approve.twig
resources/views/partials/moderation/logs/close.twig
resources/views/partials/moderation/logs/delete.twig
resources/views/partials/moderation/logs/merge.twig
resources/views/partials/moderation/logs/move.twig
resources/views/partials/moderation/logs/open.twig
resources/views/partials/moderation/logs/stick.twig
resources/views/partials/moderation/logs/unapprove.twig
resources/views/partials/moderation/logs/unstick.twig
resources/views/partials/moderation/moderation_bar.twig

Translated the other moderator tools names.

Translated mod tools

---

app/Database/Models/Conversation.php
app/Database/Models/ConversationMessage.php
app/Database/Models/ModerationLog.php
app/Database/Models/Permission.php
app/Database/Models/Poll.php
app/Database/Models/PollVote.php
app/Database/Models/Post.php
app/Database/Models/ProfileField.php
app/Database/Models/ProfileFieldGroup.php
app/Database/Models/Role.php
app/Database/Models/User.php
app/Database/Models/UserProfileField.php

Updated all Database Models to use the ::class suffix.

Update Database Models to use ::class

---

app/Database/Collections/TreeCollection.php
app/Database/Models/Forum.php
app/Database/Repositories/Eloquent/ForumRepository.php
app/Http/Controllers/ForumController.php
composer.json
composer.lock
config/app.php
resources/views/forum/all.twig
resources/views/forum/show.twig
resources/views/widgets/forum_list.twig

Remove nestedset dependency. Reduce queries on forums selection. #148

---

app/Database/Models/User.php
app/Database/Repositories/Eloquent/UserRepository.php
app/Database/Repositories/UserRepositoryInterface.php
app/Http/Controllers/Admin/Users/UserController.php
app/Http/routes.php
resources/lang/admin/en/users.php
resources/views/admin/users/list.twig

Added the ability to delete users to the User Manager in the Control Panel.

Added the ability to delete users

---

app/Database/Repositories/Eloquent/UserRepository.php
app/Database/Repositories/UserRepositoryInterface.php
app/Http/Controllers/Admin/Users/UserController.php
resources/views/admin/users/list.twig

Sorry, I kind of borked Git with the previous pull request, so I opened a new one.
The CSS probably needs to be de-inlined and a media query would be nice to make it more mobile friendly, although I'm not too familiar with SASS. Filtering by roles would be nice, although I'm not too sure about the best way to go about this.
You can currently search by username and by email by clicking on an email or inputting it (or a part of it) into the form. I'm going to leave it at this for tonight, it's getting late.
**Edit:** Almost forgot. I also added a links to the profiles.

Added basic user search.

---

storage/framework/.gitignore
storage/framework/cache/.gitignore
storage/framework/sessions/.gitignore
storage/framework/views/.gitignore
storage/framework/views/twig/.gitignore

Add sessions and similar directories

Fix #241 issues with missing sessions directory

---

README.md

Self-explanatory.
Make the README header look the way it should again.

Fix README header formatting

---

.env.example
app/Console/Commands/TaskMakeCommand.php
app/Tasking/ScheduleManager.php
composer.lock
config/app.php

This should fix error with key generation while build MyBB

Fix MyBB build

---

database/seeds/SettingsTableSeeder.php

Fix #290 Settings table seed

---

app/Form/Field.php
app/Presenters/Moderations/MovePostPresenter.php
tests/unit/Form/FieldTest.php

Getting the following error
```
Fatal error: Declaration of MyBB\Core\Form\Field::getValidationRules(): string must be compatible with MyBB\Core\Form\RenderableInterface::getValidationRules(): array
```
(#300 was half baked)

Fix incompatibility error
